import { BrokerModel } from '../models/broker.model';

export const brokers: BrokerModel [] = [
  { name: 'Allianz' },
  { name: 'AMA' },
  { name: 'AMIC' },
  { name: 'Aro' },
  { name: 'Asefa' },
  { name: 'Atlantis' },
  { name: 'AXA' },
  { name: 'Balumba' },
  { name: 'Bilbao' },
  { name: 'Caser' },
  { name: 'Catalana Occidente' },
  { name: 'DAS (asistencia)' },
  { name: 'Direct Seguros' },
  { name: 'drive&win' },
  { name: 'Europ – Assistance (Asistencia)' },
  { name: 'Fénix Directo' },
  { name: 'Fiatc' },
  { name: 'Generali' },
  { name: 'Génesis' },
  { name: 'GES' },
  { name: 'Globalty' },
  { name: 'HDI' },
  { name: 'Helvetia' },
  { name: 'Ima Ibérica' },
  { name: 'INEAS' },
  { name: 'Internauto' },
  { name: 'Legálitas (asistencia)' },
  { name: 'Liberty' },
  { name: 'Línea Directa' },
  { name: 'Mapfre' },
  { name: 'MGS' },
  { name: 'MMT' },
  { name: 'Mussap' },
  { name: 'Mutua Madrileña' },
  { name: 'Mutua Sergobina' },
  { name: 'Mutua Tinerfeña' },
  { name: 'Mutualidad de Levante' },
  { name: 'Nationale Suisse' },
  { name: 'Nuez' },
  { name: 'Ocaso' },
  { name: 'Patria Hispana' },
  { name: 'Pelayo' },
  { name: 'Penélope Seguros' },
  { name: 'Plus Ultra' },
  { name: 'PSN' },
  { name: 'Qualitas Auto' },
  { name: 'RACC' },
  { name: 'Race' },
  { name: 'Reale' },
  { name: 'Regal' },
  { name: 'Santa Lucía' },
  { name: 'SegurCaixa Adeslas' },
  { name: 'Segurísima' },
  { name: 'Soliss' },
  { name: 'Sovag' },
  { name: 'Umas' },
  { name: 'Unión Alcoyana' },
  { name: 'Verti' },
  { name: 'Vitalicio' },
  { name: 'Zurich' }
];
